server:
  servlet:
    contextPath: /EMAIL_API
  port: 8082
kai:
  name: EMAIL_API
  key: VDI0X1VUSUxfQVBJ
  threadName: EMAIL_API
  pollSize: 100
  error:
      code999: "Internal Server Error {0}"
      code998: "Timeout {0}"
      code701: "API not exist"
      code700: "API key not exists"
      code804: "Request lacks valid information"
      code803: "RequestId not exist"
      code996: "Error insert request to DB#{0}"
      code702: "API {0} not exist"
      code703: "Enquiry not exist"
      code704: "username {0} not exist"
      code705: "password {0} not exactly"
      code706: "MISSING FIELD{0}"
      code800: "Error create sessionId"
      code605: "Input OTP is invalid"
      code300: "{0}"
spring:
  application:
    name: KAIASIA_DEMO
  database:
    postgres: true
  postgredatasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://14.225.254.212:5432/KAI?currentSchema=for_test
    username: for_test
    password: for_test@2024
    maximum-pool-size: 50
    idleTimeout: 120000
    minimumIdle: 10
  jpa:
    show-sql: false
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: qthe23572@gmail.com@gmail.com
    password: quyen123@
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


dbinfo:
  apiRequest: request_in
  apiResponse: request_out
api:
  t24Api:
    apiName: T24UTILS_API
    url: http://localhost:8025/T24UTILS_API/process
    timeout: 60000
    apiKey: T24utils51klfoni1ezxl5f2ckpfx248
  ebankApi:
    apiName: EBANK_API
    url: http://localhost:8025/T24UTILS_API/process
    apiKey: custinfoq51klfoni1ezxl5f2ckpfx671
    timeout: 60000